### ISSUE TITLE
Science

### ISSUE THREAD

**Issue by MayaEnriquez** [SJSURoboticsTeam/URC-Mechanical-2024#10]
Steps for rebooting science mission:

Talk to current and past science: Viha, Tommy, Kate,
Review Past Bot: Issues 22, 24, 27, 46
Review Past Cad: https://cad.onshape.com/documents/b97908e17fca3929ddd39b66/w/d2da11b1b8072d5890f9997f/e/476a0eab40234fb23f52d635
Review Old Proposal: In Google Drive?

### Flow Path 

- 1. Collect Sample from soil
- 2. Ensure system is capable of moving while testing -- SEAL SAMPLES WITH REAGENTS!!!!
- 3. Test Alpha: Monosaccharides Test -- Heat + Benedict's Reagent + Sample + Water Yields a Green/Orange Color Reaction
- 4. Test Beta: Proteins Test -- Potassium Hydroxide + Copper Sulfate + Sample -- Purple Color Test
- 5. Possible system cleaning/filter against cross contamination
- 6. Repeat 3x -- at least 2 locations allowed for 3 -- 1 extra removable cache sample

### Collecting Samples

- [ ] End Effector able to collect deeper soil samples
- [ ] End Effector needs to be able to pull temp/humidity data from below surface level
- [ ] Arm able to reach science bot
- [ ] Funnel or opening for sample to be deposited

### Processing Samples

- [ ] Neatly hold samples: Test Tube, Revolver, etc
- [ ] Store samples(Cannot contaminate or dump)
- [ ]  Test Alpha
- [ ]  Test Beta
- [ ] Ensure proper seals and no possible spillage

### Product Considerations

- [ ] PCB + Wire Management
- [ ] Resize Science Bot accordingly - Neater assembly process preferred
- [ ] Figure out our mounting positions

**Comment by SGraysonSpangenberg** [comment]
### Goals of individual tasks -- Design Requirements
### End Effector

1. Sub 10 cm sample of 5 grams separated from the top soil above it
2. surface level sampling for life testing
3. Moisture, Temperature of sub 10cm depth sample.
4. Aim for less then 2 Kg in weight

### Sample Storage And Collection

1. Post collection the 5g sample must be stored and sealed in a system that is capable of being removed without contamination from science
2. Storage should be done in a way to also allow for testing/processing to determine life

### Processing Samples

1. "At each site the rover will need to determine the absence or presence of life... and may collect a small amount of regolith/soil for analysis by instrumentation on board the rover."
5. Stratigraphic profile and evidence of water in the profile
6. Results of on-board rover and laboratory tests performed
7. Meaning of resulting data

**Comment by SGraysonSpangenberg** [comment]
### Sources and Notes
Previous Year's Sensors and processes: 
https://docs.google.com/document/d/1NxNnKzvBrbstN7mQaU7J9C3O7eHeNqhoQLkGws0sf14/edit
Related Abstract
https://docs.google.com/document/d/1pS_YGaPwvcmqC9ZwwAFlAgUrTStsHiUPH2hkjgGjnhg/edit#heading=h.q502pa56hp42
URC 2020 Discussion -- Reminders about what is detecting life vs looking for habitability
https://docs.google.com/document/d/10YmA7fixDdeBSykO5AWw5Ahf5mXLAnm8c6KxJFx7EV8/edit
Lab related to 2024 Processes
https://bio.libretexts.org/Bookshelves/Biotechnology/Lab_Manual%3A_Introduction_to_Biotechnology/01%3A_Techniques/1.09%3A_Biomolecule_Detection
Data Sheet related to safe tubing requirements
https://www.bnl.gov/esh/shsd/pdf/compressed_gas/chem_comp_tubing_material.pdf

**Comment by SGraysonSpangenberg** [comment]
### Current Questions

- [x] Confirm Model of Spectrometer -- Unsure if using
- [ ] Define contamination (to what degree are we avoiding it)
- [x] ~~Figure out what test chemicals were originally intended to be used for detecting life~~ New tests being performed

**Comment by ouandrew** [comment]
### End Effector -- Brainstorm
 
   1. Arm bring sample to box
~2. Conveyor Belt~
~3. Yeet it~

- **Core drill** to collect sample - dump 5 g into science box, dump excess elsewhere
  - To determine 5g perhaps we can use weight sensor? I think we could just guesstimate it
  - Some sort of plunger system to push 5g sample and excess out? Shake out?
  - Soil might not be compact enough to stay in drill - could tilt horizontally
  - 
- For temp & humidity requirements, end effector to measure temperature in hole w/ smth like a meat thermometer combined with humidity sensor


**TODO** 
- Find reasonably high torque motor for drill ~(or rip a core ice drill apart)~ too expensive probably better to design own drill
~- Find viable moisture sensor~
~- Find viable temperature sensor (preferably like a meat thermometer)~
- Find viable weight sensor (maybe)? 
- Find depth sensor? Also guesstimate?
- Pressure Sensor
~- Find drill bits/design own?~ I think I found one 3.4" dia x 6" long (sorry for imperial) $20 math checks out for 5g samples:  https://www.desmos.com/calculator/hrfu2brfjw, need to find motor how to get the sample out of drill bit? 
~- Find motor~
    ~- https://www.amazon.com/7000RPM-Brushed-Torque-Electric-Geared/dp/B07TMNC1GW~
      - Use one from arm, 100-120 RPM  
- How much does the arm touch the ground/do I need to extend it
- FIND LINEAR RAIL ACTUATOR THING
- New Drill Bit: https://www.amazon.com/dp/B01N5UM01Q/ref=twister_B01N9X0VFV?_encoding=UTF8&th=1
- Start CADing once I find motor

Linear !
https://www.amazon.com/GUWANJI-SBR12-500mm-Bearings-suppoeted-500mm/dp/B08B3VDLTK/ref=sr_1_5?keywords=linear%2Brails%2B500mm&qid=1705783630&sr=8-5&th=1  - guide rails, might have?
+
https://www.omc-stepperonline.com/nema-17-non-captive-44ncm-62-31oz-in-48mm-stack-1-68a-lead-8mm-0-31496-length-200mm-17n19s1684mb4-200rs
+
https://www.amazon.com/500mm%EF%BC%8819-69-Inches%EF%BC%89Tr8x8-Thread-Printer-Machine/dp/B08JPMH4V9/ref=sr_1_6?crid=3UKM58VF6A9GL&keywords=500%2Bmm%2Blead%2Bscrew&qid=1705784403&sprefix=500%2Bmm%2Blead%2Bscre%2Caps%2C223&sr=8-6&th=1

**Sources**
Video on Perseverance's Sample Collection System
https://www.youtube.com/watch?v=l9KQjtdRPE4 
Core Ice Drill Resources
https://neem.dk/billeder/drillinguk.jpg
https://icecores.org/about-ice-cores#:~:text=Ice%20cores%20are%20typically%20drilled,with%20cutters%20at%20the%20head.
Ice Augur
https://m.media-amazon.com/images/I/51cvUGUbYpL._AC_SX679_.jpg
Perseverance Drill Bits
https://www.nasa.gov/missions/mars-2020-perseverance/perseverance-rover/nasas-perseverance-rover-gets-the-dirt-on-mars/#:~:text=As%20with%20rock%20cores%2C%20these,end%20to%20gather%20loose%20material.
https://www.nasa.gov/wp-content/uploads/2022/12/e1b-pia25590-perseverances-drill-bits-1041.jpg
https://mars.nasa.gov/mars2020/mission/status/327/why-and-how-perseverance-abrades-rocks/
Drill Bits Research
https://i.ebayimg.com/images/g/pacAAOSweW5VaWps/s-l1200.webp <- longer? can chop off and extend if we can't make own sharp things
https://www.bonanza.com/listings/3-4-Diamond-Core-Drill-Bit-6-in-deep-Holes-in-Concrete-Floor-Brick-Cement-Block/1397009738?goog_pla=1
Rock Density Table
https://www.researchgate.net/publication/327916653/figure/tbl1/AS:675497105190914@1538062468286/Rock-types-density-values.png 
Suggested Drill Speeds
https://www.udt.com.au/view/core-drilling/core-drill-data < says 3000 for wet
https://www.cessco.us/core_bits/recommended-core-bit-speed.html < 7000 (4475 - 7960)
   - " If the drilling speed is too high, the bit will polish. If the drilling speed is too low, the job will take too long. You will know if the core bit is "polished" or "glazed" when it stops cutting, you have segments left, and you don't see exposed diamonds. To open up the diamonds on the core bit, try drilling into soft abrasive material (such as a cinder block). However, try not to drill very much as you will be wasting diamonds."
https://www.ukam.com/core_drills.htm#:~:text=Recommended%20Drilling%20Speeds%20Feed%2020%20to%2035%20PSI&text=850%20to%20650%20R.P.M. < 2400 - 1000 RPM
Different Linear Systems
https://www.youtube.com/watch?v=1P6nbs1-4dQ < ball & roller need lubrication, lead not as much
https://www.youtube.com/watch?v=oEPrXljqeHA 
https://www.robotdigg.com/product/1266/spec/MTdIUzEwNzAtMTUyTjYzMzE3/ACME-lead-screw-D6.35mm-threaded-NEMA17-linear-stepper

**Comment by SGraysonSpangenberg** [comment]
### Science Black Box -- Brainstorm

**Comment by SGraysonSpangenberg** [comment]
### Parts Currently In Science Box -- This section is moving to Science_2023 #17 Science Current Inventory

1. 1x USB C Cable
2. 3x servo (2x Feetech 1x Kuman)
3. 6x Gas Sensor
4. 1x Set of PH paper
5. 2x resevoirs -- unkown material???
6. 1x Sprectrometer -- Needs to be worked on
7. 19ish magnetic detector -- Gikfun A3144
8. Probably 2x Vacuum Pump -- JY370APM
